# Generated by Django 5.0.3 on 2024-05-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_botusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botusermodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
